# Generated by Django 5.0.2 on 2024-04-01 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_order_shipping_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_packages', to='customer.customer'),
        ),
    ]
