# Generated by Django 5.0.2 on 2024-04-03 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_alter_package_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shipment',
        ),
    ]
