# Generated by Django 5.0.2 on 2024-04-08 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_delete_shipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='notification_preference',
            field=models.BooleanField(default=True),
        ),
    ]
