# Generated by Django 4.1 on 2024-04-09 18:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer", "0004_delete_shipment"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="email_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customer",
            name="notification_preference",
            field=models.BooleanField(default=True),
        ),
    ]
