# Generated by Django 4.1 on 2024-04-09 22:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("customer", "0005_customer_email_verified_and_more"),
        ("customer", "0006_customer_email_verified"),
    ]

    operations = []
