# Generated by Django 5.0.1 on 2024-01-18 01:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('origin', models.CharField(max_length=100)),
                ('distance_miles', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destination', models.CharField(default='', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stops', models.TextField()),
                ('arrival_times', models.TextField()),
                ('departure_times', models.TextField()),
                ('orders', models.ManyToManyField(to='order_management.order')),
            ],
        ),
    ]
