# Generated by Django 4.1 on 2024-04-05 19:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ('business', '0002_package_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='vehicle_id',
        ),
        migrations.AddField(
            model_name='driver',
            name='vehicle',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='drivers',
                to='business.Vehicle',
            ),
        ),
        migrations.AlterField(
            model_name='package',
            name='package_status',
            field=models.CharField(
                choices=[
                    ('processing', 'Processing'),
                    ('shipped', 'Shipped'),
                    ('delivered', 'Delivered'),
                    ('cancelled', 'Cancelled'),
                ],
                default='processing',
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]