# Generated by Django 4.1 on 2024-04-05 19:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business", "0003_remove_driver_vehicle_id_driver_vehicle_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shipment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
