# Generated by Django 5.0.3 on 2024-04-07 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_package_is_processing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='available_space',
            new_name='volume_capacity',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='status',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='weight_capacity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
