# Generated by Django 5.0.3 on 2024-04-07 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0007_rename_available_space_vehicle_volume_capacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='available_volume',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='available_weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_status',
            field=models.CharField(default='Available', max_length=50),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='volume_capacity',
            field=models.DecimalField(decimal_places=2, default=0, help_text='In cubic feet', max_digits=10),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='weight_capacity',
            field=models.DecimalField(decimal_places=2, default=0, help_text='In pounds', max_digits=10),
        ),
    ]
