# Generated by Django 5.0.3 on 2024-04-07 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0008_vehicle_available_volume_vehicle_available_weight_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='vehicle',
        ),
        migrations.RemoveField(
            model_name='package',
            name='is_processing',
        ),
        migrations.RemoveField(
            model_name='package',
            name='vehicle',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='available_volume',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='available_weight',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='volume_capacity',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='weight_capacity',
        ),
        migrations.AddField(
            model_name='driver',
            name='vehicle_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='returned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shipment',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.vehicle'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='business.driver'),
        ),
        migrations.AlterField(
            model_name='package',
            name='package_status',
            field=models.CharField(choices=[('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('returned', 'Returned')], default='processing', max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
