# Generated by Django 4.1 on 2024-04-08 03:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business", "0010_vehicle_weight_capacity"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="volume_capacity",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
