# Generated by Django 5.0.2 on 2024-04-08 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0011_vehicle_volume_capacity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='vehicle_id',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='driver',
        ),
        migrations.AddField(
            model_name='driver',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='business.vehicle'),
        ),
    ]
