# Generated by Django 4.1 on 2024-04-08 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("business", "0011_vehicle_volume_capacity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="driver",
            name="vehicle_id",
        ),
        migrations.RemoveField(
            model_name="vehicle",
            name="driver",
        ),
        migrations.AddField(
            model_name="driver",
            name="vehicle",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="business.vehicle",
            ),
        ),
    ]
