# Generated by Django 5.0.3 on 2024-04-09 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0012_remove_driver_vehicle_id_remove_vehicle_driver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
