# Generated by Django 5.0.3 on 2024-04-09 09:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0013_package_delivered_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='date_ordered',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
