# Generated by Django 5.0.3 on 2024-04-09 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0014_package_date_ordered'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='customer_email',
            field=models.EmailField(blank=True, default='', max_length=254, null=True),
        ),
    ]
