# Generated by Django 5.0.3 on 2024-04-09 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0015_package_customer_email'),
        ('customer', '0006_customer_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='order',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='package_set', to='customer.order'),
        ),
    ]
