# Generated by Django 5.0.3 on 2024-04-09 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0016_package_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
