# Generated by Django 4.1 on 2024-04-09 22:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("business", "0017_shipment_customer_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shipment",
            name="customer_email",
        ),
    ]
