# Generated by Django 5.0.1 on 2024-01-17 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('employee_id', models.CharField(max_length=10, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('driver_license', models.CharField(max_length=50)),
                ('work_permit', models.ImageField(upload_to='work_permits/')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=8)),
                ('schedule', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=10, unique=True)),
                ('model', models.CharField(max_length=30)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='driver_management.driver')),
            ],
        ),
    ]
